#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

# loads $PLAY_PARAMS 
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"
#APP_PATH="${OPENSHIFT_REPO_DIR}target/universal/stage/bin/${OPENSHIFT_APP_NAME}"
APP_PATH="${OPENSHIFT_REPO_DIR}svc/target/universal/stage/bin/svc"

if [ -f "${OPENSHIFT_REPO_DIR}target/start" ];
then
   APP_PATH="${OPENSHIFT_REPO_DIR}target/start"
   echo "Play 2.1 or earlier version"
else
   echo "Play 2.2 or later version"
fi

chmod +x ${APP_PATH}

rm -rf "${OPENSHIFT_REPO_DIR}svc/target/universal/stage/RUNNING_PID" >> /dev/null

APP_COMMAND="${APP_PATH} $PLAY_PARAMS "\
"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
"-Dhttp.address=${OPENSHIFT_DIY_IP} "\
"-Dconfig.resource=application.conf"
#"-Dconfig.resource=${OPENSHIFT_REPO_DIR}conf/application.conf"
#"-Dconfig.resource=openshift.conf"
echo "${APP_COMMAND}"

echo $APP_COMMAND &>> $LOG_FILE

#H2_TCP_CMD = "java -cp ${OPENSHIFT_REPO_DIR}svc/target/universal/stage/lib/com.h2database.h2-1.4.187.jar org.h2.tools.Server -tcp -tcpAllowOthers -tcpPort 8092"
#java -cp svc/target/universal/stage/lib/com.h2database.h2-1.4.187.jar org.h2.tools.Server -web -webAllowOthers -webPort 8082 &

#nohup bash -c "${H2_TCP_CMD} &>> ${LOG_FILE} 2>&1" &> /dev/null &
nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
