object Version {
  val APP           = "ddu-tp"
  val SCALA         = "2.11.7"
  val LOGBACK       = "1.1.2"
  val MYSQLCONN     = "5.1.36"
  val CUCUMBER      = "1.2.2"
  val DBUNIT        = "2.5.1"
  val JACKSON       = "2.6.1"
  val JACKSONMODULE = "2.6.1"
  val JUNIT         = "4.11"
  val GUICE         = "4.0"
  val JAXRS         = "3.0.9.Final"
  val JAVAEE        = "7.0"
  val HIBERNATE     = "4.3.9.Final"
  val H2            = "1.4.190"
  val SELENIUM      = "2.48.2"
  val MAILER        = "3.0.1"
  val COMMONS_LANG  = "2.6"
  val JWT           = "0.5.1"
  val MOCKITO       = "1.9.5"
  val ICAL4J        = "1.0.6"
  val DUMBSTER      = "1.9.0.2"
}
